Create Database practice;

CREATE TABLE EMPLOYEE(
	EMP_ID INT NOT NULL, 
	FIRST_NAME VARCHAR(50), 
	LAST_NAME VARCHAR(50), 
	SEX CHAR(1), 
	ACTIVE BIT DEFAULT 1 
);

SELECT FIRST_NAME, 
       LAST_NAME, 
	   DESIGNATION 
from EMPLOYEE;

SELECT DISTINCT DESIGNATION 
from EMPLOYEE;

SELECT * 
FROM EMPLOYEE 
WHERE SALARY<30000;

SELECT * 
FROM EMPLOYEE 
WHERE SALARY>45000 AND AGE<35;

SELECT * 
FROM EMPLOYEE 
WHERE SALARY>50000 AND (DESIGNATION='HR' OR DESIGNATION='TECH LEAD');

SELECT TOP 5 SALARY 
FROM EMPLOYEE 
ORDER BY SALARY DESC;

SELECT MAX(SALARY)
FROM Employee WHERE SALARY NOT IN (SELECT MAX(SALARY)
FROM Employee)

ALTER TABLE EMPLOYEE AUTO_INCREMENT;





